### ISSUE TITLE
寫一個 workflow ，在發新版本號時，更新 @v* tag

### ISSUE THREAD

**Issue by JZGoopi** [JZGoopi/releaseter#15]
### 安怎？

因為每次更新版本號時都需要手動去更新通配符版，應該直接獲取版本好的 major，然後把那個 tag 自動拿去指向最新版本的 hash 

### API 輪廓

```yaml
on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    - name: catch major tag
    - name: update major tag
        run: |
          git tag MAJOR_TAG ${{ steps.version.outputs.tag }} -f
          git push origin MAJOR_TAG -f
```
