### ISSUE TITLE
提供每個分類是否顯示的選項

### ISSUE THREAD

**Issue by JZGoopi** [JZGoopi/releaseter#7]
### 安怎？

- 有時候只是想分類而不想要讓該分類顯示
- 可以避免分類進入`其他`類中

### API 輪廓

```yaml
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'feat'
    show: false
```
