### ISSUE TITLE
提供每個分類有 except 排除的選項

### ISSUE THREAD

**Issue by JZGoopi** [JZGoopi/releaseter#8]
### 安怎？

- 有時候雖然符合了某個分類，但是不希望他進到該分類中
- 可以使用 pull 號碼來排除，又或者排除某個同時符合的 lable 名字也行
- `other` 也需要

### API 輪廓

```yaml
# 個別排除
categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'feat'
    # 排除指定 pull
    except-pull:
      - 30
      - 20
    # 排除指定 lable
    except-lable:
      - wont_release

category-other:
  show: true
  title: 'OTHERRR'
  except-pull:
    - 30
    - 20
  except-lable:
    - wont_release

# 全局排除
category-except-lable:
  - wont_release
category-except-pull:
  - 99
  - 88
```
