### ISSUE TITLE
time-format 應該可以改成 array

### ISSUE THREAD

**Issue by jzovvo** [JZGoopi/releaseter#9]
### 安怎？

- 有時候需要的格式不同，例如標題想要 06/01/02，而 tag 想要 v060102
- placeholder 可以改成 {{ $TIME_WORKFLOW_INDEX }}

### API 輪廓

```yaml
name-template: '{{ $TIME_WORKFLOW_0 }}'
tag-template: 'v{{ $TIME_WORKFLOW_1 }}'

time-format: 
  - '06/01/02 15:04:05'
  - '060102'
```
